routes/web.php
<?php

use App\Http\Controllers\LanguageController;
use App\Http\Controllers\TemplateDocController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\RefSexController;
use App\Http\Controllers\T2CardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CuratorController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\RefBankController;
use App\Http\Controllers\RefMetaController;
use App\Http\Controllers\RefOkedController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RefActionController;
use App\Http\Controllers\RefStatusController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\RefCountryController;
use App\Http\Controllers\RefDocTypeController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\BranchPhoneController;
use App\Http\Controllers\RefDocPlaceController;
use App\Http\Controllers\EmployeeTripController;
use App\Http\Controllers\RefTypePhoneController;
use App\Http\Controllers\EmployeePhoneController;
use App\Http\Controllers\EmployeeStazhController;
use App\Http\Controllers\RefTypeRodstvController;
use App\Http\Controllers\RefUserStatusController;
use App\Http\Controllers\RefVidHolidayController;
use App\Http\Controllers\BranchAddresesController;
use App\Http\Controllers\EmployeeFamilyController;
use App\Http\Controllers\EmployeeTechicController;
use App\Http\Controllers\RefAccountTypeController;
use App\Http\Controllers\RefAddressTypeController;
use App\Http\Controllers\RefFamilyStateController;
use App\Http\Controllers\RefKindHolidayController;
use App\Http\Controllers\RefNationalityController;
use App\Http\Controllers\RefPersonStateController;
use App\Http\Controllers\RefTechnicTypeController;
use App\Http\Controllers\DepartmentPhoneController;
use App\Http\Controllers\EmployeeAddressController;
use App\Http\Controllers\EmployeeHolidayController;
use App\Http\Controllers\EmployeeDocumentController;
use App\Http\Controllers\EmployeeHospitalController;
use App\Http\Controllers\EmployeeInvalideController;
use App\Http\Controllers\EmployeeMilitaryController;
use App\Http\Controllers\RefAllowanceTypeController;
use App\Http\Controllers\RefTransportTripController;
use App\Http\Controllers\EmployeeEducationController;
use App\Http\Controllers\RefVidHolidayTypeController;
use App\Http\Controllers\EmployeeDeclensionController;
use App\Http\Controllers\EmployeeTripFromToController;
use App\Http\Controllers\EmployeePayAllowanceController;
use App\Http\Controllers\EmployeeHolidaysPeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('branches', BranchController::class);
        Route::resource('companies', CompanyController::class);
        Route::get('all-branch-addreses', [
            BranchAddresesController::class,
            'index',
        ])->name('all-branch-addreses.index');
        Route::post('all-branch-addreses', [
            BranchAddresesController::class,
            'store',
        ])->name('all-branch-addreses.store');
        Route::get('all-branch-addreses/create', [
            BranchAddresesController::class,
            'create',
        ])->name('all-branch-addreses.create');
        Route::get('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'show',
        ])->name('all-branch-addreses.show');
        Route::get('all-branch-addreses/{branchAddreses}/edit', [
            BranchAddresesController::class,
            'edit',
        ])->name('all-branch-addreses.edit');
        Route::put('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'update',
        ])->name('all-branch-addreses.update');
        Route::delete('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'destroy',
        ])->name('all-branch-addreses.destroy');

        Route::resource('branch-phones', BranchPhoneController::class);
        Route::resource('curators', CuratorController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('department-phones', DepartmentPhoneController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('employee-addresses', EmployeeAddressController::class);
        Route::resource(
            'employee-declensions',
            EmployeeDeclensionController::class
        );
        Route::resource(
            'employee-documents',
            EmployeeDocumentController::class
        );
        Route::resource(
            'employee-educations',
            EmployeeEducationController::class
        );
        Route::resource('employee-families', EmployeeFamilyController::class);
        Route::resource('employee-holidays', EmployeeHolidayController::class);
        Route::resource(
            'employee-holidays-periods',
            EmployeeHolidaysPeriodController::class
        );
        Route::resource(
            'employee-hospitals',
            EmployeeHospitalController::class
        );
        Route::resource(
            'employee-invalides',
            EmployeeInvalideController::class
        );
        Route::resource(
            'employee-militaries',
            EmployeeMilitaryController::class
        );
        Route::resource(
            'employee-pay-allowances',
            EmployeePayAllowanceController::class
        );
        Route::resource('employee-phones', EmployeePhoneController::class);
        Route::resource('employee-stazhs', EmployeeStazhController::class);
        Route::resource('employee-techics', EmployeeTechicController::class);
        Route::resource('employee-trips', EmployeeTripController::class);
        Route::resource(
            'employee-trip-from-tos',
            EmployeeTripFromToController::class
        );
        Route::resource('holidays', HolidayController::class);
        Route::post('position_declensions', [PositionController::class, 'declensionPosition']);
        Route::resource('positions', PositionController::class);

        Route::resource('ref-account-types', RefAccountTypeController::class);
        Route::resource('ref-actions', RefActionController::class);
        Route::resource('ref-address-types', RefAddressTypeController::class);
        Route::resource(
            'ref-allowance-types',
            RefAllowanceTypeController::class
        );
        Route::resource('ref-banks', RefBankController::class);
        Route::resource('ref-countries', RefCountryController::class);
        Route::resource('ref-doc-places', RefDocPlaceController::class);
        Route::resource('ref-doc-types', RefDocTypeController::class);
        Route::resource('ref-family-states', RefFamilyStateController::class);
        Route::resource('ref-kind-holidays', RefKindHolidayController::class);
        Route::resource('ref-metas', RefMetaController::class);
        Route::resource('ref-nationalities', RefNationalityController::class);
        Route::resource('ref-okeds', RefOkedController::class);
        Route::resource('ref-person-states', RefPersonStateController::class);
        Route::resource('ref-sexes', RefSexController::class);
        Route::resource('ref-statuses', RefStatusController::class);
        Route::resource('ref-technic-types', RefTechnicTypeController::class);
        Route::resource(
            'ref-transport-trips',
            RefTransportTripController::class
        );
        Route::resource('ref-type-phones', RefTypePhoneController::class);
        Route::resource('ref-type-rodstvs', RefTypeRodstvController::class);
        Route::resource('ref-user-statuses', RefUserStatusController::class);
        Route::resource('ref-vid-holidays', RefVidHolidayController::class);
        Route::resource(
            'ref-vid-holiday-types',
            RefVidHolidayTypeController::class
        );
        Route::resource('t2-cards', T2CardController::class);
        Route::resource('users', UserController::class);

        Route::resource('template_docs', TemplateDocController::class);
    });

app/Models/BranchPhone.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class BranchPhone extends MainModel
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['branch_id', 'ref_type_phone_id', 'name'];

    protected $searchableFields = ['*'];

    protected $table = 'branch_phones';

    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }

    public function refTypePhone()
    {
        return $this->belongsTo(RefTypePhone::class);
    }
}

app/Http/Controllers/Api/BranchPhoneController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\BranchPhone;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\BranchPhoneResource;
use App\Http\Resources\BranchPhoneCollection;
use App\Http\Requests\BranchPhoneStoreRequest;
use App\Http\Requests\BranchPhoneUpdateRequest;

class BranchPhoneController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', BranchPhone::class);

        $search = $request->get('search', '');

        $branchPhones = BranchPhone::search($search)->paginate();

        return new BranchPhoneCollection($branchPhones);
    }

    /**
     * @param \App\Http\Requests\BranchPhoneStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BranchPhoneStoreRequest $request)
    {
        $this->authorize('create', BranchPhone::class);

        $validated = $request->validated();

        $branchPhone = BranchPhone::create($validated);

        return new BranchPhoneResource($branchPhone);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, BranchPhone $branchPhone)
    {
        $this->authorize('view', $branchPhone);

        return new BranchPhoneResource($branchPhone);
    }

    /**
     * @param \App\Http\Requests\BranchPhoneUpdateRequest $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function update(
        BranchPhoneUpdateRequest $request,
        BranchPhone $branchPhone
    ) {
        $this->authorize('update', $branchPhone);

        $validated = $request->validated();

        $branchPhone->update($validated);

        return new BranchPhoneResource($branchPhone);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, BranchPhone $branchPhone)
    {
        $this->authorize('delete', $branchPhone);

        $branchPhone->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/BranchPhoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Branch;
use App\Models\BranchPhone;
use Illuminate\Http\Request;
use App\Models\RefTypePhone;
use App\Http\Requests\BranchPhoneStoreRequest;
use App\Http\Requests\BranchPhoneUpdateRequest;

class BranchPhoneController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', BranchPhone::class);

        $search = $request->get('search', '');

        $branchPhones = BranchPhone::search($search)->paginate()
            ->withQueryString();

        return view(
            'app.branch_phones.index',
            compact('branchPhones', 'search')
        );
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', BranchPhone::class);

        $branches = Branch::pluck('id', 'id');
        $refTypePhones = RefTypePhone::pluck('id', 'id');

        return view(
            'app.branch_phones.create',
            compact('branches', 'refTypePhones')
        );
    }

    /**
     * @param \App\Http\Requests\BranchPhoneStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BranchPhoneStoreRequest $request)
    {
        $this->authorize('create', BranchPhone::class);

        $validated = $request->validated();

        $branchPhone = BranchPhone::create($validated);

        return redirect()
            ->route('branch-phones.edit', $branchPhone)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, BranchPhone $branchPhone)
    {
        $this->authorize('view', $branchPhone);

        return view('app.branch_phones.show', compact('branchPhone'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, BranchPhone $branchPhone)
    {
        $this->authorize('update', $branchPhone);

        $branches = Branch::pluck('id', 'id');
        $refTypePhones = RefTypePhone::pluck('id', 'id');

        return view(
            'app.branch_phones.edit',
            compact('branchPhone', 'branches', 'refTypePhones')
        );
    }

    /**
     * @param \App\Http\Requests\BranchPhoneUpdateRequest $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function update(
        BranchPhoneUpdateRequest $request,
        BranchPhone $branchPhone
    ) {
        $this->authorize('update', $branchPhone);

        $validated = $request->validated();

        $branchPhone->update($validated);

        return redirect()
            ->route('branch-phones.edit', $branchPhone)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\BranchPhone $branchPhone
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, BranchPhone $branchPhone)
    {
        $this->authorize('delete', $branchPhone);

        $branchPhone->delete();

        return redirect()
            ->route('branch-phones.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/branch_phones/create.blade.php
@extends('layouts.app')

@section('title')

@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('branch-phones.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.branch_phones.create_title')
            </h4>

            <x-form
                method="POST"
                action="{{ route('branch-phones.store') }}"
                class="mt-4"
            >
                @include('app.branch_phones.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('branch-phones.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/branch_phones/edit.blade.php
@extends('layouts.app')

@section('title')

@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('branch-phones.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.branch_phones.edit_title')
            </h4>

            <x-form
                method="PUT"
                action="{{ route('branch-phones.update', $branchPhone) }}"
                class="mt-4"
            >
                @include('app.branch_phones.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('branch-phones.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('branch-phones.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/branch_phones/form-inputs.blade.php
@php $editing = isset($branchPhone) @endphp

<div class="row">
    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="branch_id" label="Branch" required>
            @php $selected = old('branch_id', ($editing ? $branchPhone->branch_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>@lang('crud.please_select')</option>
            @foreach($branches as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.select
            name="ref_type_phone_id"
            label="Ref Type Phone"
            required
        >
            @php $selected = old('ref_type_phone_id', ($editing ? $branchPhone->ref_type_phone_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>@lang('crud.please_select')</option>
            @foreach($refTypePhones as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.text
            name="name"
            label="Name"
            value="{{ old('name', ($editing ? $branchPhone->name : '')) }}"
            maxlength="255"
            placeholder="Name"
            required
        ></x-inputs.text>
    </x-inputs.group>
</div>

resources/views/app/branch_phones/index.blade.php
@extends('layouts.app')

@section('title')

@endsection

@section('content')
<div class="container">
    <div class="searchbar mt-0 mb-4">
        <div class="row">
            <div class="col-md-6">
                <form>
                    <div class="input-group">
                        <input
                            id="indexSearch"
                            type="text"
                            name="search"
                            placeholder="{{ __('crud.common.search') }}"
                            value="{{ $search ?? '' }}"
                            class="form-control"
                            autocomplete="off"
                        />
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon ion-md-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6 text-right">
                @can('create', App\Models\BranchPhone::class)
                <a
                    href="{{ route('branch-phones.create') }}"
                    class="btn btn-primary"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div style="display: flex; justify-content: space-between;">
                <h4 class="card-title">
                    @lang('crud.branch_phones.index_title')
                </h4>
            </div>

            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th class="text-left">
                                @lang('crud.branch_phones.inputs.branch_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.branch_phones.inputs.ref_type_phone_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.branch_phones.inputs.name')
                            </th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($branchPhones as $branchPhone)
                        <tr>
                            <td>
                                {{ optional($branchPhone->branch)->id ?? '-' }}
                            </td>
                            <td>
                                {{ optional($branchPhone->refTypePhone)->id ??
                                '-' }}
                            </td>
                            <td>{{ $branchPhone->name ?? '-' }}</td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $branchPhone)
                                    <a
                                        href="{{ route('branch-phones.edit', $branchPhone) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $branchPhone)
                                    <a
                                        href="{{ route('branch-phones.show', $branchPhone) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $branchPhone)
                                    <form
                                        action="{{ route('branch-phones.destroy', $branchPhone) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="4">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4">{!! $branchPhones->render() !!}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/branch_phones/show.blade.php
@extends('layouts.app')

@section('title')

@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('branch-phones.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.branch_phones.show_title')
            </h4>

            <div class="mt-4">
                <div class="mb-4">
                    <h5>@lang('crud.branch_phones.inputs.branch_id')</h5>
                    <span>{{ optional($branchPhone->branch)->id ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>
                        @lang('crud.branch_phones.inputs.ref_type_phone_id')
                    </h5>
                    <span
                        >{{ optional($branchPhone->refTypePhone)->id ?? '-'
                        }}</span
                    >
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.branch_phones.inputs.name')</h5>
                    <span>{{ $branchPhone->name ?? '-' }}</span>
                </div>
            </div>

            <div class="mt-4">
                <a
                    href="{{ route('branch-phones.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\BranchPhone::class)
                <a
                    href="{{ route('branch-phones.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection