routes/web.php
<?php

use App\Http\Controllers\LanguageController;
use App\Http\Controllers\TemplateDocController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\RefSexController;
use App\Http\Controllers\T2CardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CuratorController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\RefBankController;
use App\Http\Controllers\RefMetaController;
use App\Http\Controllers\RefOkedController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RefActionController;
use App\Http\Controllers\RefStatusController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\RefCountryController;
use App\Http\Controllers\RefDocTypeController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\BranchPhoneController;
use App\Http\Controllers\RefDocPlaceController;
use App\Http\Controllers\EmployeeTripController;
use App\Http\Controllers\RefTypePhoneController;
use App\Http\Controllers\EmployeePhoneController;
use App\Http\Controllers\EmployeeStazhController;
use App\Http\Controllers\RefTypeRodstvController;
use App\Http\Controllers\RefUserStatusController;
use App\Http\Controllers\RefVidHolidayController;
use App\Http\Controllers\BranchAddresesController;
use App\Http\Controllers\EmployeeFamilyController;
use App\Http\Controllers\EmployeeTechicController;
use App\Http\Controllers\RefAccountTypeController;
use App\Http\Controllers\RefAddressTypeController;
use App\Http\Controllers\RefFamilyStateController;
use App\Http\Controllers\RefKindHolidayController;
use App\Http\Controllers\RefNationalityController;
use App\Http\Controllers\RefPersonStateController;
use App\Http\Controllers\RefTechnicTypeController;
use App\Http\Controllers\DepartmentPhoneController;
use App\Http\Controllers\EmployeeAddressController;
use App\Http\Controllers\EmployeeHolidayController;
use App\Http\Controllers\EmployeeDocumentController;
use App\Http\Controllers\EmployeeHospitalController;
use App\Http\Controllers\EmployeeInvalideController;
use App\Http\Controllers\EmployeeMilitaryController;
use App\Http\Controllers\RefAllowanceTypeController;
use App\Http\Controllers\RefTransportTripController;
use App\Http\Controllers\EmployeeEducationController;
use App\Http\Controllers\RefVidHolidayTypeController;
use App\Http\Controllers\EmployeeDeclensionController;
use App\Http\Controllers\EmployeeTripFromToController;
use App\Http\Controllers\EmployeePayAllowanceController;
use App\Http\Controllers\EmployeeHolidaysPeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('branches', BranchController::class);
        Route::resource('companies', CompanyController::class);
        Route::get('all-branch-addreses', [
            BranchAddresesController::class,
            'index',
        ])->name('all-branch-addreses.index');
        Route::post('all-branch-addreses', [
            BranchAddresesController::class,
            'store',
        ])->name('all-branch-addreses.store');
        Route::get('all-branch-addreses/create', [
            BranchAddresesController::class,
            'create',
        ])->name('all-branch-addreses.create');
        Route::get('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'show',
        ])->name('all-branch-addreses.show');
        Route::get('all-branch-addreses/{branchAddreses}/edit', [
            BranchAddresesController::class,
            'edit',
        ])->name('all-branch-addreses.edit');
        Route::put('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'update',
        ])->name('all-branch-addreses.update');
        Route::delete('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'destroy',
        ])->name('all-branch-addreses.destroy');

        Route::resource('branch-phones', BranchPhoneController::class);
        Route::resource('curators', CuratorController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('department-phones', DepartmentPhoneController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('employee-addresses', EmployeeAddressController::class);
        Route::resource(
            'employee-declensions',
            EmployeeDeclensionController::class
        );
        Route::resource(
            'employee-documents',
            EmployeeDocumentController::class
        );
        Route::resource(
            'employee-educations',
            EmployeeEducationController::class
        );
        Route::resource('employee-families', EmployeeFamilyController::class);
        Route::resource('employee-holidays', EmployeeHolidayController::class);
        Route::resource(
            'employee-holidays-periods',
            EmployeeHolidaysPeriodController::class
        );
        Route::resource(
            'employee-hospitals',
            EmployeeHospitalController::class
        );
        Route::resource(
            'employee-invalides',
            EmployeeInvalideController::class
        );
        Route::resource(
            'employee-militaries',
            EmployeeMilitaryController::class
        );
        Route::resource(
            'employee-pay-allowances',
            EmployeePayAllowanceController::class
        );
        Route::resource('employee-phones', EmployeePhoneController::class);
        Route::resource('employee-stazhs', EmployeeStazhController::class);
        Route::resource('employee-techics', EmployeeTechicController::class);
        Route::resource('employee-trips', EmployeeTripController::class);
        Route::resource(
            'employee-trip-from-tos',
            EmployeeTripFromToController::class
        );
        Route::resource('holidays', HolidayController::class);
        Route::post('position_declensions', [PositionController::class, 'declensionPosition']);
        Route::resource('positions', PositionController::class);

        Route::resource('ref-account-types', RefAccountTypeController::class);
        Route::resource('ref-actions', RefActionController::class);
        Route::resource('ref-address-types', RefAddressTypeController::class);
        Route::resource(
            'ref-allowance-types',
            RefAllowanceTypeController::class
        );
        Route::resource('ref-banks', RefBankController::class);
        Route::resource('ref-countries', RefCountryController::class);
        Route::resource('ref-doc-places', RefDocPlaceController::class);
        Route::resource('ref-doc-types', RefDocTypeController::class);
        Route::resource('ref-family-states', RefFamilyStateController::class);
        Route::resource('ref-kind-holidays', RefKindHolidayController::class);
        Route::resource('ref-metas', RefMetaController::class);
        Route::resource('ref-nationalities', RefNationalityController::class);
        Route::resource('ref-okeds', RefOkedController::class);
        Route::resource('ref-person-states', RefPersonStateController::class);
        Route::resource('ref-sexes', RefSexController::class);
        Route::resource('ref-statuses', RefStatusController::class);
        Route::resource('ref-technic-types', RefTechnicTypeController::class);
        Route::resource(
            'ref-transport-trips',
            RefTransportTripController::class
        );
        Route::resource('ref-type-phones', RefTypePhoneController::class);
        Route::resource('ref-type-rodstvs', RefTypeRodstvController::class);
        Route::resource('ref-user-statuses', RefUserStatusController::class);
        Route::resource('ref-vid-holidays', RefVidHolidayController::class);
        Route::resource(
            'ref-vid-holiday-types',
            RefVidHolidayTypeController::class
        );
        Route::resource('t2-cards', T2CardController::class);
        Route::resource('users', UserController::class);

        Route::resource('template_docs', TemplateDocController::class);
    });

app/Http/Controllers/Api/RefAllowanceTypeController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Models\RefAllowanceType;
use App\Http\Controllers\Controller;
use App\Http\Resources\RefAllowanceTypeResource;
use App\Http\Resources\RefAllowanceTypeCollection;
use App\Http\Requests\RefAllowanceTypeStoreRequest;
use App\Http\Requests\RefAllowanceTypeUpdateRequest;

class RefAllowanceTypeController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', RefAllowanceType::class);

        $search = $request->get('search', '');

        $refAllowanceTypes = RefAllowanceType::search($search)->paginate();

        return new RefAllowanceTypeCollection($refAllowanceTypes);
    }

    /**
     * @param \App\Http\Requests\RefAllowanceTypeStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(RefAllowanceTypeStoreRequest $request)
    {
        $this->authorize('create', RefAllowanceType::class);

        $validated = $request->validated();

        $refAllowanceType = RefAllowanceType::create($validated);

        return new RefAllowanceTypeResource($refAllowanceType);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\RefAllowanceType $refAllowanceType
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, RefAllowanceType $refAllowanceType)
    {
        $this->authorize('view', $refAllowanceType);

        return new RefAllowanceTypeResource($refAllowanceType);
    }

    /**
     * @param \App\Http\Requests\RefAllowanceTypeUpdateRequest $request
     * @param \App\Models\RefAllowanceType $refAllowanceType
     * @return \Illuminate\Http\Response
     */
    public function update(
        RefAllowanceTypeUpdateRequest $request,
        RefAllowanceType $refAllowanceType
    ) {
        $this->authorize('update', $refAllowanceType);

        $validated = $request->validated();

        $refAllowanceType->update($validated);

        return new RefAllowanceTypeResource($refAllowanceType);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\RefAllowanceType $refAllowanceType
     * @return \Illuminate\Http\Response
     */
    public function destroy(
        Request $request,
        RefAllowanceType $refAllowanceType
    ) {
        $this->authorize('delete', $refAllowanceType);

        $refAllowanceType->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/RefAllowanceTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use App\Models\RefAllowanceType;
use App\Http\Requests\RefAllowanceTypeStoreRequest;
use App\Http\Requests\RefAllowanceTypeUpdateRequest;
use Illuminate\Http\Response;

class RefAllowanceTypeController extends Controller
{
    /**
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', RefAllowanceType::class);

        $search = $request->get('search', '');

        $refAllowanceTypes = RefAllowanceType::search($search)
            ->paginate()
            ->withQueryString();

        return view(
            'app.ref_allowance_types.index',
            compact('refAllowanceTypes', 'search')
        );
    }

    /**
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function create(Request $request)
    {
        $this->authorize('create', RefAllowanceType::class);

        return view('app.ref_allowance_types.create');
    }

    /**
     * @param RefAllowanceTypeStoreRequest $request
     * @return Response
     */
    public function store(RefAllowanceTypeStoreRequest $request)
    {
        $this->authorize('create', RefAllowanceType::class);

        $validated = $request->validated();

        $refAllowanceType = new RefAllowanceType();
        $refAllowanceType = $this->save($validated, $refAllowanceType);

        return redirect()
            ->route('ref-allowance-types.edit', $refAllowanceType)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param Request $request
     * @param RefAllowanceType $refAllowanceType
     * @return Response
     * @throws AuthorizationException
     */
    public function show(Request $request, RefAllowanceType $refAllowanceType)
    {
        $this->authorize('view', $refAllowanceType);

        return view(
            'app.ref_allowance_types.show',
            compact('refAllowanceType')
        );
    }

    /**
     * @param Request $request
     * @param RefAllowanceType $refAllowanceType
     * @return Response
     * @throws AuthorizationException
     */
    public function edit(Request $request, RefAllowanceType $refAllowanceType)
    {
        $this->authorize('update', $refAllowanceType);

        return view(
            'app.ref_allowance_types.edit',
            compact('refAllowanceType')
        );
    }

    /**
     * @param RefAllowanceTypeUpdateRequest $request
     * @param RefAllowanceType $refAllowanceType
     * @return Response
     * @throws AuthorizationException
     */
    public function update(
        RefAllowanceTypeUpdateRequest $request,
        RefAllowanceType $refAllowanceType
    ) {
        $this->authorize('update', $refAllowanceType);

        $validated = $request->validated();

        $this->save($validated, $refAllowanceType);

        return redirect()
            ->route('ref-allowance-types.edit', $refAllowanceType)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param Request $request
     * @param RefAllowanceType $refAllowanceType
     * @return Response
     * @throws AuthorizationException
     */
    public function destroy(
        Request $request,
        RefAllowanceType $refAllowanceType
    ) {
        $this->authorize('delete', $refAllowanceType);

        $refAllowanceType->delete();

        return redirect()
            ->route('ref-allowance-types.index')
            ->withSuccess(__('crud.common.removed'));
    }

    private function save($validated, $model)
    {
        foreach($validated['name'] as $lang => $value){
            $model->translateOrNew($lang)->name = $value;
        }
        $model->save();
        return $model;
    }
}

resources/views/app/ref_allowance_types/create.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_allowance_types.create_title')
@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <x-form
                method="POST"
                action="{{ route('ref-allowance-types.store') }}"
            >
                @include('app.ref_allowance_types.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('ref-allowance-types.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/ref_allowance_types/edit.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_allowance_types.edit_title')
@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <x-form
                method="PUT"
                action="{{ route('ref-allowance-types.update', $refAllowanceType) }}"
            >
                @include('app.ref_allowance_types.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('ref-allowance-types.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('ref-allowance-types.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/ref_allowance_types/form-inputs.blade.php
@php $editing = isset($refAllowanceType) @endphp

<div class="row">
    <div class="col-lg-12 col-12 col-sm-12">
        @include('components.lang_name_array_edit', ['model' => ($editing) ? $refAllowanceType : null, 'editing' => $editing, 'noCol' => true])
    </div>
</div>

resources/views/app/ref_allowance_types/index.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_allowance_types.index_title')
@endsection

@section('content')
<div class="container">
    <div class="searchbar mt-0 mb-4">
        <div class="row">
            <div class="col-md-6">
                <form>
                    <div class="input-group">
                        <input
                            id="indexSearch"
                            type="text"
                            name="search"
                            placeholder="{{ __('crud.common.search') }}"
                            value="{{ $search ?? '' }}"
                            class="form-control"
                            autocomplete="off"
                        />
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon ion-md-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6 text-right">
                @can('create', App\Models\RefAllowanceType::class)
                <a
                    href="{{ route('ref-allowance-types.create') }}"
                    class="btn btn-primary"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th>@lang('crud.names')</th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($refAllowanceTypes as $refAllowanceType)
                        <tr>
                            <td>{{ $refAllowanceType->name }}</td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $refAllowanceType)
                                    <a
                                        href="{{ route('ref-allowance-types.edit', $refAllowanceType) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $refAllowanceType)
                                    <a
                                        href="{{ route('ref-allowance-types.show', $refAllowanceType) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $refAllowanceType)
                                    <form
                                        action="{{ route('ref-allowance-types.destroy', $refAllowanceType) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="1">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="1">
                                {!! $refAllowanceTypes->render() !!}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/ref_allowance_types/show.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_allowance_types.show_title')
@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="mt-4"></div>

            <div class="mt-4">
                <a
                    href="{{ route('ref-allowance-types.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\RefAllowanceType::class)
                <a
                    href="{{ route('ref-allowance-types.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection