routes/web.php
<?php

use App\Http\Controllers\LanguageController;
use App\Http\Controllers\TemplateDocController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\RefSexController;
use App\Http\Controllers\T2CardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CuratorController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\RefBankController;
use App\Http\Controllers\RefMetaController;
use App\Http\Controllers\RefOkedController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RefActionController;
use App\Http\Controllers\RefStatusController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\RefCountryController;
use App\Http\Controllers\RefDocTypeController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\BranchPhoneController;
use App\Http\Controllers\RefDocPlaceController;
use App\Http\Controllers\EmployeeTripController;
use App\Http\Controllers\RefTypePhoneController;
use App\Http\Controllers\EmployeePhoneController;
use App\Http\Controllers\EmployeeStazhController;
use App\Http\Controllers\RefTypeRodstvController;
use App\Http\Controllers\RefUserStatusController;
use App\Http\Controllers\RefVidHolidayController;
use App\Http\Controllers\BranchAddresesController;
use App\Http\Controllers\EmployeeFamilyController;
use App\Http\Controllers\EmployeeTechicController;
use App\Http\Controllers\RefAccountTypeController;
use App\Http\Controllers\RefAddressTypeController;
use App\Http\Controllers\RefFamilyStateController;
use App\Http\Controllers\RefKindHolidayController;
use App\Http\Controllers\RefNationalityController;
use App\Http\Controllers\RefPersonStateController;
use App\Http\Controllers\RefTechnicTypeController;
use App\Http\Controllers\DepartmentPhoneController;
use App\Http\Controllers\EmployeeAddressController;
use App\Http\Controllers\EmployeeHolidayController;
use App\Http\Controllers\EmployeeDocumentController;
use App\Http\Controllers\EmployeeHospitalController;
use App\Http\Controllers\EmployeeInvalideController;
use App\Http\Controllers\EmployeeMilitaryController;
use App\Http\Controllers\RefAllowanceTypeController;
use App\Http\Controllers\RefTransportTripController;
use App\Http\Controllers\EmployeeEducationController;
use App\Http\Controllers\RefVidHolidayTypeController;
use App\Http\Controllers\EmployeeDeclensionController;
use App\Http\Controllers\EmployeeTripFromToController;
use App\Http\Controllers\EmployeePayAllowanceController;
use App\Http\Controllers\EmployeeHolidaysPeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('branches', BranchController::class);
        Route::resource('companies', CompanyController::class);
        Route::get('all-branch-addreses', [
            BranchAddresesController::class,
            'index',
        ])->name('all-branch-addreses.index');
        Route::post('all-branch-addreses', [
            BranchAddresesController::class,
            'store',
        ])->name('all-branch-addreses.store');
        Route::get('all-branch-addreses/create', [
            BranchAddresesController::class,
            'create',
        ])->name('all-branch-addreses.create');
        Route::get('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'show',
        ])->name('all-branch-addreses.show');
        Route::get('all-branch-addreses/{branchAddreses}/edit', [
            BranchAddresesController::class,
            'edit',
        ])->name('all-branch-addreses.edit');
        Route::put('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'update',
        ])->name('all-branch-addreses.update');
        Route::delete('all-branch-addreses/{branchAddreses}', [
            BranchAddresesController::class,
            'destroy',
        ])->name('all-branch-addreses.destroy');

        Route::resource('branch-phones', BranchPhoneController::class);
        Route::resource('curators', CuratorController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('department-phones', DepartmentPhoneController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('employee-addresses', EmployeeAddressController::class);
        Route::resource(
            'employee-declensions',
            EmployeeDeclensionController::class
        );
        Route::resource(
            'employee-documents',
            EmployeeDocumentController::class
        );
        Route::resource(
            'employee-educations',
            EmployeeEducationController::class
        );
        Route::resource('employee-families', EmployeeFamilyController::class);
        Route::resource('employee-holidays', EmployeeHolidayController::class);
        Route::resource(
            'employee-holidays-periods',
            EmployeeHolidaysPeriodController::class
        );
        Route::resource(
            'employee-hospitals',
            EmployeeHospitalController::class
        );
        Route::resource(
            'employee-invalides',
            EmployeeInvalideController::class
        );
        Route::resource(
            'employee-militaries',
            EmployeeMilitaryController::class
        );
        Route::resource(
            'employee-pay-allowances',
            EmployeePayAllowanceController::class
        );
        Route::resource('employee-phones', EmployeePhoneController::class);
        Route::resource('employee-stazhs', EmployeeStazhController::class);
        Route::resource('employee-techics', EmployeeTechicController::class);
        Route::resource('employee-trips', EmployeeTripController::class);
        Route::resource(
            'employee-trip-from-tos',
            EmployeeTripFromToController::class
        );
        Route::resource('holidays', HolidayController::class);
        Route::post('position_declensions', [PositionController::class, 'declensionPosition']);
        Route::resource('positions', PositionController::class);

        Route::resource('ref-account-types', RefAccountTypeController::class);
        Route::resource('ref-actions', RefActionController::class);
        Route::resource('ref-address-types', RefAddressTypeController::class);
        Route::resource(
            'ref-allowance-types',
            RefAllowanceTypeController::class
        );
        Route::resource('ref-banks', RefBankController::class);
        Route::resource('ref-countries', RefCountryController::class);
        Route::resource('ref-doc-places', RefDocPlaceController::class);
        Route::resource('ref-doc-types', RefDocTypeController::class);
        Route::resource('ref-family-states', RefFamilyStateController::class);
        Route::resource('ref-kind-holidays', RefKindHolidayController::class);
        Route::resource('ref-metas', RefMetaController::class);
        Route::resource('ref-nationalities', RefNationalityController::class);
        Route::resource('ref-okeds', RefOkedController::class);
        Route::resource('ref-person-states', RefPersonStateController::class);
        Route::resource('ref-sexes', RefSexController::class);
        Route::resource('ref-statuses', RefStatusController::class);
        Route::resource('ref-technic-types', RefTechnicTypeController::class);
        Route::resource(
            'ref-transport-trips',
            RefTransportTripController::class
        );
        Route::resource('ref-type-phones', RefTypePhoneController::class);
        Route::resource('ref-type-rodstvs', RefTypeRodstvController::class);
        Route::resource('ref-user-statuses', RefUserStatusController::class);
        Route::resource('ref-vid-holidays', RefVidHolidayController::class);
        Route::resource(
            'ref-vid-holiday-types',
            RefVidHolidayTypeController::class
        );
        Route::resource('t2-cards', T2CardController::class);
        Route::resource('users', UserController::class);

        Route::resource('template_docs', TemplateDocController::class);
    });

app/Models/TemplateDoc.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class TemplateDoc extends MainModel
{
    use HasFactory;
    use Searchable;
    use SoftDeletes;

    use Translatable;

    public $translatedAttributes = ['name', 'body'];

    protected $table = 'template_docs';

    protected $fillable = ['id_type'];

    protected $searchableFields = ['*'];

    public function templateDocTranslations(): HasMany
    {
        return $this->hasMany(TemplateDocTranslation::class);
    }

    public static function listTypes(): array
    {
        return [
            [
                'id' => 0,
                'name' => __('crud.id_types.pattern')
            ],
            [
                'id' => 1,
                'name' => __('crud.id_types.document')
            ]
        ];
    }
}

app/Http/Controllers/TemplateDocController.php
<?php

namespace App\Http\Controllers;

use App\Models\TemplateDoc;
use App\Models\TemplateDocTranslation;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class TemplateDocController extends Controller
{
    public $idTypes = [];

    public function __construct()
    {
        $this->idTypes = [
            [
                'id' => 0,
                'name' => __('crud.id_types.pattern')
            ],
            [
                'id' => 1,
                'name' => __('crud.id_types.document')
            ]
        ];
    }

    /**
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', TemplateDoc::class);

        $search = $request->get('search', '');

        if($search !== ''){
            $res = TemplateDocTranslation::query()
                ->where('name')
                ->pluck('template_doc_id')
                ->toArray();

            $templateDocs = TemplateDoc::query()
                ->whereIn('id', $res)
                ->paginate()
                ->withQueryString();
        }else{
            $templateDocs = TemplateDoc::query()
                ->paginate()
                ->withQueryString();
        }


        return view('app.template_docs.index', compact('templateDocs', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('create', TemplateDoc::class);

        $types = $this->idTypes;
        return view('app.template_docs.create', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', TemplateDoc::class);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $this->authorize('show', TemplateDoc::class);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $this->authorize('update', TemplateDoc::class);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('update', TemplateDoc::class);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->authorize('delete', TemplateDoc::class);
    }
}

resources/views/app/template_docs/create.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_sexes.create_title')
@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <x-form
                method="POST"
                action="{{ route('ref-sexes.store') }}"
                id="save_form_template"
            >
                @include('app.template_docs.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('ref-sexes.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    @include('app.template_docs.script')
@endsection

resources/views/app/template_docs/edit.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_sexes.edit_title')
@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <x-form
                method="PUT"
                action="{{ route('ref-sexes.update', $refSex) }}"
            >
                @include('app.template_docs.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('ref-sexes.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('ref-sexes.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/template_docs/form-inputs.blade.php
@php
    $editing = isset($template_doc);

    $emp = new \App\Models\Employee();
    $markers = $emp->getAllAttributes();
@endphp


<ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
    @foreach(config('panel.available_languages', []) as $lang=>$title)
        <li class="nav-item">
            <a class="nav-link {{ ($lang == app()->getLocale()) ? 'active' : '' }}"
               id="custom-tabs-{{ $lang }}-tab"
               data-toggle="pill"
               href="#custom-tabs-{{ $lang }}"
               role="tab"
               aria-controls="custom-tabs-{{ $lang }}"
               aria-selected="true"
            >{{ $title }}</a>
        </li>
    @endforeach
</ul>

<div class="row mt-2">
    <div class="col-lg-9">

        <div class="tab-content" id="custom-tabs-one-tabContent">
            @foreach(config('panel.available_languages', []) as $lang=>$title)
                <div class="tab-pane fade {{ ($lang == app()->getLocale()) ? 'active show' : '' }}"
                     id="custom-tabs-{{ $lang }}" role="tabpanel"
                     aria-labelledby="custom-tabs-{{ $lang }}-tab"
                >
                    <div class="row">
                        <div class="col-lg-12 col-12 col-sm-12">
                            <div class="form-group">
                                <label>{{ __('crud.report_name') }}</label>
                                <input type="text"
                                       class="form-control"
                                       name="name[{{ $lang }}]"
                                       placeholder="{{ __('crud.report_name') }}"
                                       value="{{ old('name', ($editing ? $template_doc->translation($lang)->name : '')) }}"
                                       required
                                >
                            </div>
                        </div>
                        <main class="col-lg-12 col-12 col-sm-12">
                            <div class="toolbar-container-{{ $lang }}"></div>
                            <div class="content-container">
                                <div class="form-control editor editor_{{ $lang }}" id="editor_{{ $lang }}"></div>
                                <textarea name="body[{{ $lang }}]" id="body_{{ $lang }}"
                                          style="display: none"></textarea>
                            </div>
                        </main>
                    </div>


                </div>
            @endforeach
        </div>

    </div>
    <div class="col-lg-3">
        <label>{{ __('crud.report_markers') }}</label>
        <input type="text" class="form-control" id="search_marker" value=""
               placeholder="{{ __('crud.common.search') }}">

        <div style="height: 80vh; overflow-y: auto; margin-top: 15px">
            @foreach($markers as $marker)
                <span class="btn btn-default btn-sm btn-block marker"
                      data-call="{{ $marker['call'] }}"
                >{{ $marker['title'] }}</span>
            @endforeach
        </div>
    </div>
</div>

resources/views/app/template_docs/index.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.default_title.index')
@endsection

@section('content')
<div class="container">
    <div class="searchbar mt-0 mb-4">
        <div class="row">
            <div class="col-md-6">
                <form>
                    <div class="input-group">
                        <input
                            id="indexSearch"
                            type="text"
                            name="search"
                            placeholder="{{ __('crud.common.search') }}"
                            value="{{ $search ?? '' }}"
                            class="form-control"
                            autocomplete="off"
                        />
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon ion-md-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6 text-right">
                @can('create', App\Models\TemplateDoc::class)
                <a
                    href="{{ route('template_docs.create') }}"
                    class="btn btn-primary"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th>@lang('crud.names')</th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($templateDocs as $templateDoc)
                        <tr>
                            <td>{{ $templateDoc->name }}</td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $templateDoc)
                                    <a
                                        href="{{ route('template_docs.edit', $templateDoc) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $templateDoc)
                                    <a
                                        href="{{ route('template_docs.show', $templateDoc) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $templateDoc)
                                    <form
                                        action="{{ route('template_docs.destroy', $templateDoc) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="1">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="1">{!! $templateDocs->render() !!}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/template_docs/script.blade.php
<script src="{{ asset('ckeditor/translations/ru.js') }}"></script>
<script src="{{ asset('ckeditor/js/ckeditor.js') }}"></script>
{{--<script src="{{ asset('ckeditor/js/ckbox.js') }}"></script>--}}
<script>
    let editors = [];
    let editPanel = [];
    @foreach(config('panel.available_languages', []) as $lang=>$title)
    DecoupledEditor
        .create(document.querySelector('#editor_{{ $lang }}'), {
            // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
        })
        .then(editor => {
            const toolbarContainer = document.querySelector('.toolbar-container-{{ $lang }}');

            toolbarContainer.prepend(editor.ui.view.toolbar.element);

            editPanel.push(editor);
            // window.editor = editor;
        })
        .catch(err => {
            console.error(err.stack);
        });
    editors.push("{{ $lang }}");
    @endforeach

    $('#save_form_template').on('submit', function(event){
        event.preventDefault();

        $.each(editors, function(i, lng){
            let html = $("#editor_"+lng).html();
            console.log(lng, html);
        })
    })

    $('#search_marker').bind("change paste keyup", function(){
        let text = $(this).val();
        $('.marker').each(function(i, item){
            let html = item.innerHTML.toUpperCase();
            if(html.indexOf(text.toUpperCase()) < 0){
                item.style.display = 'none';
            }else{
                item.style.display ='block';
            }
        })
    })

    $('.marker').click(function(){
        let data = $(this).attr('data-call');
        let text = $(this).html();
        let lang = $('.nav-link.active').attr('id').replaceAll('custom-tabs-', '').replaceAll('-tab', '');
        let index = editors.indexOf(lang);

        let content = '<a href="#'+data+'">'+text+'</a>';

        // content = '<span style="color:hsl(210, 75%, 60%);">Данные сотрудника - Дата принятия</span>';

        const viewFragment = editPanel[index].data.processor.toView( content );
        const modelFragment = editPanel[index].data.toModel( viewFragment );
        editPanel[index].model.insertContent( modelFragment );
    })
</script>

resources/views/app/template_docs/show.blade.php
@extends('layouts.app')

@section('title')
    @lang('crud.ref_sexes.show_title')
@endsection

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="mt-0">
                @include('components.lang_name_array_show', ['model' => $refSex])
            </div>

            <div class="mt-4">
                <a href="{{ route('ref-sexes.index') }}" class="btn btn-light">
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\RefSex::class)
                <a href="{{ route('ref-sexes.create') }}" class="btn btn-light">
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection